# Generated by Django 4.2.4 on 2023-09-01 05:08

import app_posts.validation_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/', validators=[app_posts.validation_functions.image_size_validation]),
        ),
    ]
