# Generated by Django 4.2.4 on 2023-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0003_alter_appuser_managers_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_profile_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
